### ISSUE TITLE
Some  errors in def concat_shuffle_split(x, y)

### ISSUE THREAD

**Issue by r1c7** [TropComplique/shufflenet-v2-tensorflow#2]
`batch_size = shape[0]      
height, width = shape[1], shape[2]`    
should be
`batch_size = x.shape[0].value        
height, width = x.shape[1].value, x.shape[2].value`

**Comment by TropComplique** [comment]
Hi. 
If we assume that the shape is static then your correction is right.

But I assume that batch size and image size aren't necessarily static values.
So I can feed the network with variable size images or batches.

**Comment by r1c7** [comment]
Thanks for explaination.
